apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: compare-engine-listener-interceptor
  name: compare-engine-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-compare-engine-listener-interceptor
