apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  labels:
    app: sso
  name: marrober
  namespace: keycloak-system
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    email: marrober@redhat.com
    enabled: true
    emailVerified: true
    credentials:
      - type: "password"
        value: "secure"
    firstName: Mark
    lastName: Roberts
    username: marrober