apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .SpokeRolebindingName }}-agent
  namespace: {{ .AddonInstallNamespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - open-cluster-management.io
    resources:
      - clustercollectors
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - open-cluster-management.io
    resources:
      - clustercollectors/status
    verbs:
      - update
      - patch
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
      - clusteroperators
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
    verbs:
      - get
      - list
      - watch
