apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-left-namespace
  namespace: right
spec:
  podSelector:
    matchLabels:
      deployment: third
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          projectName: left
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-right-namespace
  namespace: left
spec:
  podSelector:
    matchLabels:
      deployment: second
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          projectName: right
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: right
  name: deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-third-to-fourth
  namespace: right
spec:
  podSelector:
    matchLabels:
      deployment: third
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          projectName: right
    - podSelector:
        matchLabels:
          deployment: fourth
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-third-to-fourth
  namespace: right
spec:
  podSelector:
    matchLabels:
      deployment: fourth
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          projectName: right
    - podSelector:
        matchLabels:
          deployment: third
  policyTypes:
  - Ingress










  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-left-namespace
    namespace: right
  spec:
    podSelector:
      matchLabels:
        deployment: two
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            projectName: left
        podSelector:
          matchLabels:
            deployment: one
---
