apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${PROJECT_NAME}
    labels:
      aspect: ${ASPECT}
  spec: {}
  status: {}
parameters:
- name: PROJECT_NAME
- name: ASPECT