apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-compare
  namespace: openshift-gitops
spec:
  description: Applications related to cluster compare process

  sourceRepos:
  - '*'
  - https://github.com/marrober/development

  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'addon.open-cluster-management.io'
    kind: '*'
  - group: 'cluster.open-cluster-management.io'
    kind: '*'
  - group: 'apiextensions.k8s.io:'
    kind: '*'

  roles:
  - name: developer
    groups:
    - developers
    policies:
    - p, proj:cluster-compare:developer, applications, get, *, allow
    - p, proj:cluster-compare:developer, applications, sync, *, allow  