apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-compare

resources:
- namespace.yaml
- postgrescluster.yaml
- db-configmap.yaml
- deployment.yaml
- role-bindings/engine-role.yaml
- role-bindings/engine-role-bindings.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/marrober/cluster-compare-engine
  newTag: tvsxs
