apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-compare

resources:
- namespace.yaml
- postgrescluster.yaml
- db-configmap.yaml
- deployment.yaml
- rolebindings/engine-role.yaml
- rolebindings/engine-role-bindings.yaml
images:
- name: quay.io/marrober/cluster-compare-engine
  newTag: j2pc8
