apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-compare

resources:
- namespace.yaml
- postgrescluster.yaml
- db-configmap.yaml
images:
- name: quay.io/marrober/cluster-compare-engine
  newTag: mgr2r
