kind: Service
apiVersion: v1
metadata:
  name: cluster-compare-engine
  namespace: cluster-compare
  labels:
    app.kubernetes.io/name: cluster-compare-engine
spec:
  ports:
    - name: 8443-tcp
      protocol: TCP
      port: 443
      targetPort: 8443
  tls:
    termination: edge
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cluster-compare-engine