apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-compare-engine-mcm-reader
rules:
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - open-cluster-management.io
    resources:
      - clustercollectors
    verbs:
      - list
      - get
      - watch
