apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- addon-template.yaml
- cluster-management-addon.yaml
- cluster-role.yaml
- placement.yaml
- role-bindings/addon-template-role-bindings.yaml
- role-bindings/addon-template-role.yaml

images:
- name: quay.io/marrober/cluster-compare-collector
  newTag: '1'
