apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- addon-template.yaml
- cluster-management-addon.yaml
- cluster-role.yaml
- clustercollector-crd.yaml
- placement.yaml
- role-bindings/addon-template-role-bindings.yaml
- role-bindings/addon-template-role.yaml

images:
- name: quay.io/marrober/cluster-compare-collector
  newTag: h45m4

commonAnnotations:
  addon.open-cluster-management.io/image-version: quay.io/marrober/cluster-compare-collector:88f6q

patches:
- patch: |
    - op: add
      path: /spec/agentSpec/workload/manifests/4/metadata/annotations
      value:
        cluster-collector.addon/image-image: quay.io/marrober/cluster-compare-collector:h45m4
  target:
    kind: AddOnTemplate
    name: clustercollector
