apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- role-binding/argocd-admin-role.yaml
- pipelines/pipeline.yaml
- tasks/build.yaml
- tasks/git-clone.yaml
- tasks/pushImageToOCPImageStream.yaml
- tasks/update-and-commit-dev-env.yaml
- triggers/eventListener.yaml
- triggers/eventListenerRoute.yaml
- triggers/triggerBinding.yaml
- triggers/triggerTemplate.yaml
- image-streams/terminal.yaml