FROM source-image
USER 0
WORKDIR /opt/app-root/src/

COPY . .
# Drop any host node_modules and install production deps into the image.
RUN rm -rf node_modules \
  && npm ci --omit=dev \
  && chmod a+w /var/log \
  && chown -R 1001:0 /opt/app-root/src

USER 1001
CMD ["npm", "start"]
