apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image-to-quay
spec:
  params:
    - name: quay-instance-url
      type: string
    - name: quay-account
      type: string
    - name: quay-repository
      type: string
    - name: STORAGE_DRIVER
      type: string
    - name: TLSVERIFY
      type: string
    - name: imageTag
      type: string
  steps:
    - name: push-to-quay
      script: >-
        #!/usr/bin/env bash

        set +x

        buildah push --storage-driver=$(params.STORAGE_DRIVER) \

        --tls-verify=$(params.TLSVERIFY) --root /files/buildah-containers \

        localhost/cluster-collector:latest \

        docker://quay.io/$(params.quay-io-account)/$(params.quay-io-repository):$(params.imageTag)  
      image: registry.redhat.io/rhel8/buildah    
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      resources: {}        
      volumeMounts:
        - name: quay-auth-secret
          mountPath: /etc/secret-volume
          readOnly: true
  volumes:
    - name: quay-auth-secret
      secret:
        secretName: quay-auth-secret
  workspaces:
  - name: files
    mountPath: /files
