apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment-etherpad.yaml         
- deployment-postgres-sql.yaml
- etherpad-route.yaml      
- etherpad-service.yaml    
- etherpad-settings.yaml   
- postgres-sql-secret.yaml
- postgressql.yaml
- postgres-pvc.yaml