apiVersion: v1
data:
  database-name: ZXRoZXJwYWQ=
  database-password: ZXRoZXI=
  database-user: ZXRoZXI=
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: etherpad_db
    template: postgresql-persistent-template
  name: postgresql
type: Opaque
