//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCollector) DeepCopyInto(out *ClusterCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCollector.
func (in *ClusterCollector) DeepCopy() *ClusterCollector {
	if in == nil {
		return nil
	}
	out := new(ClusterCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCollectorList) DeepCopyInto(out *ClusterCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCollectorList.
func (in *ClusterCollectorList) DeepCopy() *ClusterCollectorList {
	if in == nil {
		return nil
	}
	out := new(ClusterCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCollectorSpec) DeepCopyInto(out *ClusterCollectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCollectorSpec.
func (in *ClusterCollectorSpec) DeepCopy() *ClusterCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCollectorStatus) DeepCopyInto(out *ClusterCollectorStatus) {
	*out = *in
	out.ClusterVersion = in.ClusterVersion
	if in.ClusterOperators != nil {
		in, out := &in.ClusterOperators, &out.ClusterOperators
		*out = make([]ClusterOperatorSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InstalledOperators != nil {
		in, out := &in.InstalledOperators, &out.InstalledOperators
		*out = make([]InstalledOperatorSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCollectorStatus.
func (in *ClusterCollectorStatus) DeepCopy() *ClusterCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperatorSnapshot) DeepCopyInto(out *ClusterOperatorSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperatorSnapshot.
func (in *ClusterOperatorSnapshot) DeepCopy() *ClusterOperatorSnapshot {
	if in == nil {
		return nil
	}
	out := new(ClusterOperatorSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersionSnapshot) DeepCopyInto(out *ClusterVersionSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersionSnapshot.
func (in *ClusterVersionSnapshot) DeepCopy() *ClusterVersionSnapshot {
	if in == nil {
		return nil
	}
	out := new(ClusterVersionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledOperatorSnapshot) DeepCopyInto(out *InstalledOperatorSnapshot) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledOperatorSnapshot.
func (in *InstalledOperatorSnapshot) DeepCopy() *InstalledOperatorSnapshot {
	if in == nil {
		return nil
	}
	out := new(InstalledOperatorSnapshot)
	in.DeepCopyInto(out)
	return out
}
