apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: collector-addon-template
spec:
  params:
  - name: gitrepository.url
  - name: gitrevision
  - name: branch
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-1-run-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: collector-addon
      params:
        - name: GIT_REPO
          value: $(tt.params.gitrepository.url)
        - name: GIT_REVISION
          value: $(tt.params.gitrevision)
        - name: GIT_REPO_NAME
          value: development
        - name: app-dir
          value: development/openshift/cluster-compare/collector-addon/app
        - name: dockerfile
          value: Dockerfile
        - name: image-short-name
          value: cluster-collector
        - name: imagestream-url
          value: default-route-openshift-image-registry.apps.ocp4.mr-openshift.co.uk/$(context.taskRun.namespace)/cluster-collector
          ## Update Kustomize file for the deployment of the application to development      
        - name: repo_type
          value: github.com
        - name: cd-git-url
          value: marrober/development
        - name: cd-git-repo-name
          value: development
        - name: cd-git-repo-path-to-content-development
          value: openshift/cluster-compare/collector-addon/deploy
        - name: cd-git-commit-comment-dev
          value: "Update from ci process - dev"
        - name: cd-git-user-name
          value: "Mark Roberts"
        - name: cd-git-user-email
          value: "mroberts@redhat.com"
        - name: quay-instance-url
          value: "quay.io"
        - name: quay-account
          value: "marrober"
        - name: quay-repository
          value: "cluster-compare-collector" 



      workspaces:
      - name: files
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      - name: resources
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
