apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: localstack
    app.kubernetes.io/component: localstack
    app.kubernetes.io/instance: localstack
  name: localstack
  namespace: localstack
  resourceVersion: "228433"
  uid: 6122abfb-70e4-4372-b79b-1971b86dafa8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: localstack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: localstack
    spec:
      containers:
      - image: localstack/localstack@sha256:049c1db1d4349d2b7bd2c7910ef86b325cf75776a686ecfb7b962d5a5023540f
        imagePullPolicy: IfNotPresent
        name: localstack
        env:
        - name: AWS_DEFAULT_REGION
          value: sa-east-1
        - name: AWS_ACCESS_KEY_ID
          value: admin
        - name: AWS_SECRET_ACCESS_KEY
          value: admin
        - name: DEFAULT_REGION
          value: sa-east-1
        ports:
        - containerPort: 4541
          protocol: TCP
        - containerPort: 4551
          protocol: TCP
        - containerPort: 4557
          protocol: TCP
        - containerPort: 4528
          protocol: TCP
        - containerPort: 4529
          protocol: TCP
        - containerPort: 4533
          protocol: TCP
        - containerPort: 4531
          protocol: TCP
        - containerPort: 4535
          protocol: TCP
        - containerPort: 4539
          protocol: TCP
        - containerPort: 4545
          protocol: TCP
        - containerPort: 4554
          protocol: TCP
        - containerPort: 4514
          protocol: TCP
        - containerPort: 4516
          protocol: TCP
        - containerPort: 4517
          protocol: TCP
        - containerPort: 4556
          protocol: TCP
        - containerPort: 5678
          protocol: TCP
        - containerPort: 4549
          protocol: TCP
        - containerPort: 4553
          protocol: TCP
        - containerPort: 4566
          protocol: TCP
        - containerPort: 4521
          protocol: TCP
        - containerPort: 4522
          protocol: TCP
        - containerPort: 4544
          protocol: TCP
        - containerPort: 4548
          protocol: TCP
        - containerPort: 4555
          protocol: TCP
        - containerPort: 4513
          protocol: TCP
        - containerPort: 4519
          protocol: TCP
        - containerPort: 4525
          protocol: TCP
        - containerPort: 4538
          protocol: TCP
        - containerPort: 4543
          protocol: TCP
        - containerPort: 4526
          protocol: TCP
        - containerPort: 4534
          protocol: TCP
        - containerPort: 4536
          protocol: TCP
        - containerPort: 4530
          protocol: TCP
        - containerPort: 4537
          protocol: TCP
        - containerPort: 4540
          protocol: TCP
        - containerPort: 4558
          protocol: TCP
        - containerPort: 4510
          protocol: TCP
        - containerPort: 4520
          protocol: TCP
        - containerPort: 4527
          protocol: TCP
        - containerPort: 4518
          protocol: TCP
        - containerPort: 4523
          protocol: TCP
        - containerPort: 4524
          protocol: TCP
        - containerPort: 4547
          protocol: TCP
        - containerPort: 4552
          protocol: TCP
        - containerPort: 4511
          protocol: TCP
        - containerPort: 4512
          protocol: TCP
        - containerPort: 4515
          protocol: TCP
        - containerPort: 4559
          protocol: TCP
        - containerPort: 4550
          protocol: TCP
        - containerPort: 4532
          protocol: TCP
        - containerPort: 4542
          protocol: TCP
        - containerPort: 4546
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/localstack
          name: localstack-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: localstack-volume-1
