---

- hosts: localhost
  tasks:
  - name: check ocp api is available
    ansible.builtin.uri:
      url: https://api.{{ cluster_deployment.clusterName }}.{{ cluster_deployment.baseDomain }}:6443/healthz
      validate_certs: false

  - name: check ocp webconsole is available
    ansible.builtin.uri:
      url: https://console-openshift-console.apps.{{ cluster_deployment.clusterName }}.{{ cluster_deployment.baseDomain }}/
      validate_certs: false

