kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: delete-replicaset
  namespace: cluster-compare
rules:
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - delete
      - list
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-delete-replicaset
  namespace: cluster-compare
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: cluster-compare
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: delete-replicaset
