apiVersion: v1
kind: Service
metadata:
  labels:
    app: first
    app.kubernetes.io/component: first
    app.kubernetes.io/instance: first
  name: first
  namespace: service-mesh-tracing
spec:
  ports:
  - name: http-8080
    port: 8080
    targetPort: 8080
  selector:
    deployment: first
