apiVersion: v1
kind: Service
metadata:
  labels:
    app: fourth
    app.kubernetes.io/component: fourth
    app.kubernetes.io/instance: fourth
  name: fourth
  namespace: service-mesh-tracing
spec:
  type: ClusterIP
  ports:
  - name: http-8080
    port: 8080
    targetPort: 8080
  selector:
    deployment: fourth
