# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - verify
  - build
  - dockerfile-build
  - image-build
  - scan-image
  - merge-sboms
  - sbom
  - security

#build-job:
#  rules:
#  - changes:
#    - 'docs/**/*'
#    - 'mkdocs.yaml'
#  variables:
#    ENTITY_NAMESPACE: 'default'
#    ENTITY_KIND: 'Component'
#    ENTITY_NAME: my-quarkus-app
#  image: quay.io/redhat-gpte/techdocs-cli
#  stage: build
#  script:
#  - techdocs-cli generate --no-docker --verbose
#  - techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --awsEndpoint $AWS_ENDPOINT --awsS3ForcePathStyle --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME

verify-commit-job:
  stage: verify
  allow_failure: true
  # Define variables that correspond to the Tekton parameters
  variables:
    # Description: TUF mirror
    TUF_MIRROR: "http://tuf.trusted-artifact-signer.svc"
    # Description: Email address of committer
    CERTIFICATE_IDENTITY: "user1@demo.redhat.com"
    # Description: OIDC issuer
    OIDC_ISSUER: "https://keycloak-rhsso.apps.cluster-ztdj6.ztdj6.sandbox388.opentlc.com/auth/realms/openshift"
    # Description: Rekor URL
    REKOR_URL: "http://rekor-server.trusted-artifact-signer.svc"
  # Use the same base image as the Tekton task's step
  image: alpine/git:latest
  # The 'before_script' runs before the main 'script' of the job
  before_script:
    # Set the GITSIGN_REKOR_URL environment variable, mirroring the Tekton stepTemplate
    - export GITSIGN_REKOR_URL=$REKOR_URL
    # Install dependencies
    - apk add rpm cosign
    # Download and install gitsign
    - wget -q https://github.com/sigstore/gitsign/releases/download/v0.13.0/gitsign_0.13.0_linux_amd64.rpm
    - rpm -ivh gitsign_0.13.0_linux_amd64.rpm
    # Configure safe directory for git operations
    - git config --global --add safe.directory $CI_PROJECT_DIR
    # Initialize cosign
    - cosign initialize --mirror=$TUF_MIRROR --root=$TUF_MIRROR/root.json
  script:
    # The main script commands to verify the commit
    - pwd

    - echo "This job verifies the latest commit signature"
    - git show -s
    - gitsign verify --certificate-identity=$CERTIFICATE_IDENTITY --certificate-oidc-issuer=$OIDC_ISSUER HEAD 

source-sbom:
  stage: build
  image: quay.io/redhat-appstudio/syft:v0.94.0

  script:
    - mkdir syft-output
    - syft dir:$CI_PROJECT_DIR/pacman/src --output cyclonedx-json=syft-output/sbom-source-cyclonedx.json
    - syft dir:$CI_PROJECT_DIR/pacman/src --output spdx-json=syft-output/sbom-source-spdx.json
    - cat syft-output/sbom-source-spdx.json

  artifacts:
    paths:
      - syft-output/
    expire_in: 1 hour

build-job:
  stage: build
  # Specify the custom container image to use for this job
  image: registry.redhat.io/rhel9/nodejs-16@sha256:bb841b3993ebd175034990b72ea7f556b82dbf64f77e96daf60f03b9b0689b61
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "buildah-sa"

  script:
    # Execute the specific commands
    - mkdir -p build_output/
    - echo "Another file" > build_output/new-file.txt

    - cd "$CI_PROJECT_DIR/pacman/src"
    - ls -al
    - npm install -g npm@9.2.0
    - npm install
    - ls -al
    - cd $CI_PROJECT_DIR
    - ls -al
    - cp -R $CI_PROJECT_DIR/pacman/src/* build_output/
    - ls -al build_output/

  artifacts:
    paths:
      - build_output/
    expire_in: 1 hour



build-image:
  stage: image-build
  allow_failure: true
  image: quay.io/marrober/buildah-for-gitlab-runners:3
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    FQ_IMAGE_NAME:  quay.io/marrober/pacman-glr:latest
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "buildah-sa"
    DOCKER_AUTH_CONFIG: $DOCKER_AUTH_CONFIG
  script:
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - ls -al ~/.docker/config.json
    - cd $CI_PROJECT_DIR/pacman/src/
    - buildah bud --layers -f dockerfile -t $FQ_IMAGE_NAME
    - buildah images 
    - buildah push --tls-verify=false --authfile /home/build/.docker/config.json $FQ_IMAGE_NAME


scan-image:
  stage: scan-image
  image: quay.io/marrober/ubi:latest
  variables:
    FQ_IMAGE_NAME:  quay.io/marrober/pacman-glr:latest

  script:
    - |
      set +e
       mkdir acs-output
      curl -s -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./acs-output/roxctl > /dev/null; echo "Getting roxctl"
      chmod u+x acs-output/roxctl
      failTask="false"
      echo "image to be processed : $FQ_IMAGE_NAME"
      echo "image scan ....."
      ./acs-output/roxctl image scan --image $FQ_IMAGE_NAME --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT --force > image-scan.txt 
      echo "image check ...."
      ./acs-output/roxctl image check --image $FQ_IMAGE_NAME --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT -o table --retries 0 > image-check.txt || ROX_EXIT_CODE=$?
      echo $ROX_EXIT_CODE
      echo "image sbom ...."
      ./acs-output/roxctl image sbom --image $FQ_IMAGE_NAME -e $ROX_CENTRAL_ENDPOINT --insecure-skip-tls-verify > container-sbom.json
      cp image-scan.txt acs-output/
      cp container-sbom.json acs-output/
      cp image-check.txt acs-output/
      ls -al acs-output/
      echo "image check result ....."
      cat image-check.txt
      cat container-sbom.json

      exit $ROX_EXIT_CODE


  artifacts:
    paths:
      - acs-output/
    expire_in: 1 hour

merge-syft-sboms-job:
  stage: merge-sboms
  image: registry.access.redhat.com/ubi9/python-39:1-143.1696863474
  script:
    - |
      #!/usr/bin/env bash
      ls -al acs-output
      ls -al syft-output
      mkdir merged-sboms
      python3 <<'EOF'
      import json

      # load SBOMs
      with open("./acs-output/container-sbom.json") as f:
          image_sbom = json.load(f)

      with open("./syft-output/sbom-source-spdx.json") as f:
          source_sbom = json.load(f)

      # fetch unique packages from available SBOMs
      def get_identifier(package):
          return package["name"] + '@' + package.get("versionInfo", "")

      image_sbom_packages = image_sbom.get("packages", [])
      initial_image_SBOM_elements = str(len(image_sbom_packages))
      existing_packages = [get_identifier(package) for package in image_sbom_packages]

      source_sbom_packages = source_sbom.get("packages", [])
      initial_source_SBOM_elements = str(len(source_sbom_packages))
      added_package_counter = 0
      package_match = 0
      for package in source_sbom_packages:
          if get_identifier(package) not in existing_packages:
              image_sbom_packages.append(package)
              existing_packages.append(get_identifier(package))
              added_package_counter = added_package_counter + 1
          else:
            package_match = package_match + 1
              
      image_sbom_packages.sort(key=lambda c: get_identifier(c))

      print("image sbom elements : " + initial_image_SBOM_elements)
      print("source sbom elements : " + initial_source_SBOM_elements)
      print("added packages : " + str(added_package_counter))
      print("matched packages : " + str(package_match))
      print("image sbom elements (after merge) : " + str(len(image_sbom_packages)))

      # write the CycloneDX unified SBOM
      with open("./sbom-cyclonedx.json", "w") as f:
          json.dump(image_sbom, f, indent=4)
      EOF
      ls -al sbom-cyclonedx.json
      cat sbom-cyclonedx.json
      cp sbom-cyclonedx.json merged-sboms/

  artifacts:
    paths:
      - merged-sboms/
    expire_in: 1 hour

upload-sbom-to-repo:
  stage: security 
  image: ubi9/ubi
  allow_failure: true
  variables:
    CYCLONEDX_HOST_URL: "https://cyclonedx-bom-repo-server-cyclonedx.apps.cluster-ztdj6.ztdj6.sandbox388.opentlc.com"
  script:
    - |
      set +x

      echo "check sbom in location"
      ls -al merged-sboms

      curl -X POST "${CYCLONEDX_HOST_URL}/v1/bom" -H "Content-Type: application/vnd.cyclonedx+json; version=1.4" -H "Accept: */*" -d @merged-sboms/sbom-cyclonedx.json -D /tmp/header.txt 
      cat /tmp/header.txt 
      LOCATION=$(cat /tmp/header.txt | grep location: | awk '{print $2}' | sed 's|http:|https:|g' | tr -d '\r')
      echo "Captured location: $LOCATION"
      echo "LINK_TO_SBOM=$LOCATION" > job.env
    
  artifacts:
    reports:
      dotenv: job.env

Upload-sbom-to-tpa:
  stage: sbom
  image: quay.io/redhat-appstudio/appstudio-utils:5bd7d6cb0b17f9f2eab043a8ad16ba3d90551bc2@sha256:8c7fcf86af40c71aeb58e4279625c8308af5144e2f6b8e28b0ec7e795260e5f7
  variables:
    # --- Tekton Params translated to GitLab CI variables ---
    COMPONENT_ID: "your-application-name" # Replace with your component identifier
    SBOMS_DIR: "."
    HTTP_RETRIES: "3"
    FAIL_IF_TRUSTIFICATION_NOT_CONFIGURED: "true"
    # WORKDIR within the container for temporary storage
    CI_UPLOAD_WORKDIR: "./upload_temp"

    # --- Trustification Secret Variables (Defined in GitLab Project/Group Settings) ---
    # These variables must be configured in GitLab Settings -> CI/CD -> Variables.
    # Set them as 'Masked' and 'Protected' (optional).
    BOMBASTIC_API_URL: $BOMBASTIC_API_URL
    OIDC_ISSUER_URL: $OIDC_ISSUER_URL
    OIDC_CLIENT_ID: $OIDC_CLIENT_ID
    OIDC_CLIENT_SECRET: $OIDC_CLIENT_SECRET
    # Optional variable:
    SUPPORTED_CYCLONEDX_VERSION: $SUPPORTED_CYCLONEDX_VERSION
  
  # Define cache/artifacts to persist files generated in 'gather-sboms' for subsequent steps
  cache:
    paths:
      - ./upload_temp
  artifacts:
    paths:
      - ./upload_temp
    expire_in: 1 day

  script:
    # --- Step 1: gather-sboms logic ---
    - |
      #!/usr/bin/env bash
      set -o errexit -o nounset -o pipefail
      echo "--- Executing gather-sboms logic ---"

      mkdir -p "$CI_UPLOAD_WORKDIR"

      version_lesser_equal() {
        local first
        first="$(printf "%s\n%s" "$1" "$2" | sort --version-sort | head -n 1)"
        [ "$1" = "$first" ]
      }

      if [[ -n "$SUPPORTED_CYCLONEDX_VERSION" ]]; then
        supported_version="$SUPPORTED_CYCLONEDX_VERSION"
        echo "Supported CycloneDX version found in variables: $supported_version"
      else
        echo "SUPPORTED_CYCLONEDX_VERSION not set, will not check SBOM versions"
        supported_version=""
      fi
      
      echo $supported_version

      filepath="merged-sboms/sbom-cyclonedx.json"

      echo "File to upload : $filepath"
        
      jq --arg nn "pacman-glr:latest" '.name = $nn' $filepath > temp-sbom.json
      mv temp-sbom.json sbom-cyclonedx.json

      filepath="sbom-cyclonedx.json"
        
      # Calculate SBOM ID (checksum) and symlink to WORKDIR
      sbom_id="sha256:$(sha256sum "$filepath" | cut -d ' ' -f 1)"
      sbom_path="$CI_UPLOAD_WORKDIR/$sbom_id.json"
      
      # Use cp instead of ln -s because GitLab CI artifacts/caching often dereferences links
      cp "$(realpath "$filepath")" "$sbom_path"

      ls -al $sbom_path

      if [[ -n "$supported_version" ]]; then
        sbom_version="$(jq -r ".specVersion" "$sbom_path")"

        if version_lesser_equal "$sbom_version" "$supported_version"; then
          echo "SBOM version ($sbom_version) is supported (<= $supported_version), will not convert"
        else
          echo "SBOM version ($sbom_version) is not supported, will convert to $supported_version"
          printf "%s" "$supported_version" > "${sbom_path}.convert_to_version"
        fi
      fi

      echo "Found $(find "$CI_UPLOAD_WORKDIR" -name "*.json" | wc -l) CycloneDX SBOMs ready for processing"
    
    # --- Step 2: convert-sboms-if-needed logic ---
    # This step requires a different tool (syft), so we use 'after_script' to change image for this block
    # Note: Using a single image with both tools (jq, find, syft) would be simpler if possible.
    # We use 'before_script' here to change the execution context for this specific script block.
    - |
      #!/usr/bin/env bash
      set -o errexit -o nounset -o pipefail
      echo "--- Executing convert-sboms-if-needed logic ---"

      # Install Syft within the current container as we cannot easily change the image mid-script in GitLab CI
      # The original image 'appstudio-utils' is used, installing syft temporarily.
      # If you have a custom runner image with both tools, use that instead.
      
      curl -sL raw.githubusercontent.com | sh -s -- -b /usr/local/bin
      echo "here-1"
      if ! command -v syft &> /dev/null; then
          echo "Syft installation failed. Cannot proceed with conversion."
          exit 1
      fi

      echo "here-2"

      shopt -s nullglob
      for sbom_path in "$CI_UPLOAD_WORKDIR"/*.json; do
        conversion_attr="${sbom_path}.convert_to_version"

        if [[ -f "$conversion_attr" ]]; then
          cdx_version="$(cat "$conversion_attr")"
          original_sbom_path="$(realpath "$sbom_path")"

          echo "Converting $original_sbom_path to CycloneDX $cdx_version"
          # Output converted version to a new file path to not overwrite original input
          syft convert "$original_sbom_path" -o "cyclonedx-json@${cdx_version}=${sbom_path}.supported_version"
        else
          # Original SBOM already has a supported CDX version, duplicate it for next step input
          cp "$sbom_path" "${sbom_path}.supported_version"
        fi
      done
    
    # --- Step 3: upload-sboms logic ---
    - |
      #!/usr/bin/env bash
      set -o errexit -o nounset -o pipefail
      echo "--- Executing upload-sboms logic ---"

      shopt -s nullglob
      # Look for files ending in .json.supported_version created in the previous step
      sboms_to_upload=("$CI_UPLOAD_WORKDIR"/*.json.supported_version)

      if [[ "${#sboms_to_upload[@]}" -eq 0 ]]; then
        echo "No SBOMs to upload found in $CI_UPLOAD_WORKDIR."
        exit 0
      fi

      # Check for required configuration variables in GitLab CI environment
      check_config() {
        local config_keys=("BOMBASTIC_API_URL" "OIDC_ISSUER_URL" "OIDC_CLIENT_ID" "OIDC_CLIENT_SECRET")
        for key in "${config_keys[@]}"; do
          if [[ -z "${!key}" ]]; then
            echo "Missing required configuration variable: $key" >&2
            return 1
          fi
        done
        return 0
      }

      if ! check_config; then
        if [[ "$FAIL_IF_TRUSTIFICATION_NOT_CONFIGURED" == "true" ]]; then
          echo "Trustification configuration is incomplete. Failing pipeline."
          exit 1
        else
          echo "Trustification configuration is incomplete. Skipping upload as requested."
          exit 0
        fi
      fi

      # Upload logic (using curl, same as original Tekton task)
      for sbom_path in "${sboms_to_upload[@]}"; do
        sbom_id=$(basename "$sbom_path" .json.supported_version)
        echo "Uploading $sbom_path (ID: $sbom_id)"

        # OIDC authentication steps must happen here to get a fresh token
        AUTH_TOKEN=$(curl -sX POST "$OIDC_ISSUER_URL/protocol/openid-connect/token" \
          -d "grant_type=client_credentials" \
          -d "client_id=$OIDC_CLIENT_ID" \
          -d "client_secret=$OIDC_CLIENT_SECRET" \
          -d 'scope=openid' | jq -r '.access_token')

        if [[ -z "$AUTH_TOKEN" ]] || [[ "$AUTH_TOKEN" == "null" ]]; then
          echo "Failed to retrieve OIDC token. Check credentials."
          exit 1
        fi

        # Use curl to upload the SBOM
        curl -X POST "$BOMBASTIC_API_URL/api/v1/sbom?id=$sbom_id" \
          -H "Authorization: Bearer $AUTH_TOKEN" \
          --retry "$HTTP_RETRIES" \
          --retry-delay 5 \
          --data-binary "@$sbom_path"
        
        echo "" # Newline for readability
      done

      echo "Finished uploading all discovered SBOMs."
  