# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - dockerfile-build
  - image-build
  - scan-image

#build-job:
#  rules:
#  - changes:
#    - 'docs/**/*'
#    - 'mkdocs.yaml'
#  variables:
#    ENTITY_NAMESPACE: 'default'
#    ENTITY_KIND: 'Component'
#    ENTITY_NAME: my-quarkus-app
#  image: quay.io/redhat-gpte/techdocs-cli
#  stage: build
#  script:
#  - techdocs-cli generate --no-docker --verbose
#  - techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --awsEndpoint $AWS_ENDPOINT --awsS3ForcePathStyle --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME

build-job:
  stage: build
  # Specify the custom container image to use for this job
  image: registry.redhat.io/rhel9/nodejs-16@sha256:bb841b3993ebd175034990b72ea7f556b82dbf64f77e96daf60f03b9b0689b61
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "buildah-sa"

  script:
    # Execute the specific commands
    - mkdir -p build_output/
    - echo "Another file" > build_output/new-file.txt

    - cd "$CI_PROJECT_DIR/pacman/src"
    - ls -al
    - npm install -g npm@9.2.0
    - npm install
    - ls -al
    - cd $CI_PROJECT_DIR
    - ls -al
    - cp -R $CI_PROJECT_DIR/pacman/src/* build_output/
    - ls -al build_output/

  artifacts:
    paths:
      - build_output/
    expire_in: 1 hour

build-image:
  stage: image-build
  image: quay.io/marrober/buildah-gitlab-runner:1
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
    FQ_IMAGE_NAME: default-route-openshift-image-registry.apps.cluster-ztdj6.ztdj6.sandbox388.opentlc.com/gitlab/pacman:latest
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: "buildah-sa"
  before_script:
    # Log in to the GitLab container registry
    # - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah login default-route-openshift-image-registry.apps.cluster-ztdj6.ztdj6.sandbox388.opentlc.com --username admin --password "sha256~mKmXFo_IOoxR2zq2XhkDLjZVn3vRniij5Lby49thRg4" -v
    - buildah images
    - cd $CI_PROJECT_DIR/pacman/src/
    - buildah bud --layers -f dockerfile -t $FQ_IMAGE_NAME
    - buildah images
    - buildah push $FQ_IMAGE_NAME    

scan-image:
  stage: scan-image
  image: quay.io/marrober/ubi:latest

  script:
    ls -al
  